function allbacInfo=twoWayClusterTree(bioTree,bacteriaFrameInfo)
bacteriaLength=40;
amp=2000;
colorChoose=zeros(1000,3);
colorChoose(:,1)=0.5;
colorChoose(1:200,:)=colormap(jet(200));
% close all
[bioTree,branchList,~,~]=myBiograph_new2(bioTree);
[bioTree,branchList,allList]=divisionFinder(bioTree,branchList);
allbacInfo=getAllBacForFrame(bacteriaFrameInfo,bioTree,size(bioTree,2));
numRadius=zeros(size(branchList,1),2);
orderNum=1:size(allbacInfo.bacteriaInfo,1);
for i=1:size(branchList,1)
    orderNum1=orderNum(allbacInfo.bacteriaInfo(:,5)==i);
    numRadius(i,1)=numel(orderNum1);
    if numRadius(i,1)>=2
        icentroid=allbacInfo.centroidInfo(allbacInfo.bacteriaInfo(:,5)==i,:);
        properCentroid=[mean(icentroid(:,1)),mean(icentroid(:,2))];
        numRadius(i,2)=(mean(pdist2(icentroid,properCentroid).^2)).^0.5;
    end
end
numRadius(numRadius(:,1)<=1,:)=[];
numRadius=numRadius(:,end:-1:1);
numRadius(:,1)=numRadius(:,1)/bacteriaLength;
numRadius(:,1)=numRadius(:,1).^2;
numRad=twoDimGaussian(numRadius);
h=createSurfacefigure(numRad.y',numRad.x',numRad.Image*amp,colorChoose,size(bioTree,2));
end
function allbacInfo=getAllBacForFrame(bacteriaFrameInfo,bioTree,iframe)
nbac=0;
for i=1:iframe-1
    for iLeaf=1:size(bioTree{i}.leavies,2);
        is2Node=bioTree{i}.leavies{iLeaf}.is2Node;
        nbac=nbac+1;
        if is2Node==1
            preNode=bioTree{i}.leavies{iLeaf}.nodeInfo;
            preNodeTraceSize=size(bioTree{preNode(1)}.node{preNode(2)}.Out{preNode(3)}.traceInfo.measurment,2);
            bacteriaInfo(nbac,:)=[preNode(1),preNode(2),preNode(3),preNodeTraceSize,bioTree{preNode(1)}.node{preNode(2)}.branchIndex,0];
            centroidInfo(nbac,:)=bioTree{preNode(1)}.node{preNode(2)}.Out{preNode(3)}.traceInfo.measurment{end}.Centroid;
        else
            preRoot=bioTree{i}.leavies{iLeaf}.rootInfo;
            preRootTraceSize=size(bioTree{preRoot(1)}.root{preRoot(2)}.traceInfo.measurment,2);
            bacteriaInfo(nbac,:)=[preRoot(1),preRoot(2),0,preRootTraceSize,bioTree{preRoot(1)}.root{preRoot(2)}.branchIndex,0];
            centroidInfo(nbac,:)=bioTree{preRoot(1)}.root{preRoot(2)}.traceInfo.measurment{end}.Centroid;
        end
    end
end
bacteriaInfo(nbac+1:nbac+size(bacteriaFrameInfo{iframe}.bacteriaInfo,1),1:5)=bacteriaFrameInfo{iframe}.bacteriaInfo;
bacteriaInfo(nbac+1:nbac+size(bacteriaFrameInfo{iframe}.bacteriaInfo,1),6)=1;
centroidInfo(nbac+1:nbac+size(bacteriaFrameInfo{iframe}.bacteriaInfo,1),:)=bacteriaFrameInfo{iframe}.centroidInfo;
allbacInfo.bacteriaInfo=bacteriaInfo;
allbacInfo.centroidInfo=centroidInfo;
end
function result=twoDimGaussian(degreeRadius)
xMin=0;
yMin=0;
xMax=1200;
yMax=100;
sigma1=20;
interval1=12;
sigma2=2;
interval2=1;
rowPos=xMin:interval1:xMax;
rowPos=rowPos';
columnPos=yMin:interval2:yMax;
resultImage=zeros(numel(rowPos),numel(columnPos));
for i=1:size(degreeRadius,1)
%     disp(i)
    rowGauss=1/(2*pi)^0.5/sigma1*exp(-(rowPos-degreeRadius(i,1)).^2/2/sigma1^2);
    columnGauss=1/(2*pi)^0.5/sigma2*exp(-(columnPos-degreeRadius(i,2)).^2/2/sigma2^2);
    resultImage=resultImage+rowGauss*columnGauss;
end
result.Image=resultImage;
result.numPoint=size(degreeRadius,1);
result.x=rowPos';
result.y=columnPos;
end
function h=createSurfacefigure(xdata,ydata,zdata,colorChoose,i)
%CREATEFIGURE(ZDATA1,YDATA1,XDATA1,CDATA1)
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 16-Apr-2013 19:57:26

% Create figure
figure1 = figure;
% Create axes
axes1 = axes('Parent',figure1);
xlim(axes1,[0 100]);
ylim(axes1,[0 1200]);
hold(axes1,'all');

% Create surface
surface('Parent',axes1,'ZData',zdata,'YData',ydata,'XData',xdata,'CData',zdata,...
    'LineStyle','none');
colorChoose=colorChoose(1:ceil(max(max(zdata))),:);
colormap(colorChoose)
% Create title
title(strcat('frameNum=',num2str(i)),'FontSize',20);

% Create xlabel
xlabel('degreeNum','FontSize',20);

% Create ylabel
ylabel('radius of gyration(/40pixel)','FontSize',20);
h=gcf;
end        
