function  [lifeTime,eventCount,serchingRasuid,allR]=explorBranchList(bioTree,branchList,allList)
lifeTime=[];
windowTime=120;
endTime=size(bioTree,2);
timeCount=0:windowTime:endTime;
divisionCount=zeros(1,size(timeCount,2));
hyperNodeCount=zeros(1,size(timeCount,2));
serchingRasuid=[];
timeBin=0:360:size(bioTree,2);
for iList=1:size(branchList,1)
    branchInfo=branchList(iList,1:2);
    allRoot=bioTree{branchInfo(1)}.node{branchInfo(2)}.allRoot;
    allNode=bioTree{branchInfo(1)}.node{branchInfo(2)}.allNode;
    lifeTime=[lifeTime,max(allNode(:,1))-min(allRoot(:,1))];
end
allNode=allList.allNode;
for iTime=1:size(timeCount,2)
    divisionCount(iTime)=size(allNode(allNode(:,1)>=timeCount(iTime)& allNode(:,1)<timeCount(iTime)+windowTime & allNode(:,4)==1,:),1);
    hyperNodeCount(iTime)=size(allNode(allNode(:,1)>=timeCount(iTime)& allNode(:,1)<timeCount(iTime)+windowTime & allNode(:,5)==1,:),1);
end
eventCount=[timeCount',divisionCount',hyperNodeCount'];
for iframe=1:size(bioTree,2)
    if ~isempty(bioTree{iframe}.root)
        for iroot=1:size(bioTree{iframe}.root,2)
            if bioTree{iframe}.root{iroot}.is2Node==false
                leafInfo=bioTree{iframe}.root{iroot}.leafInfo;
                startXY=bioTree{iframe}.root{iroot}.rootMeasurment.Centroid;
                endXY=bioTree{leafInfo(1)}.leavies{leafInfo(2)}.leafMeasurment.Centroid;
                serchingRasuid=[serchingRasuid,sqrt((startXY(1)- endXY(1))^2+(startXY(2)- endXY(2))^2)];
            end
        end
    end
end
allR.lifeTime=lifeTime;
allR.eventCount=eventCount;
allR.serchingRasuid=serchingRasuid;
[count,n]=hist(lifeTime,timeBin);
createLifeTimefigure(timeBin, count);
end
function createLifeTimefigure(xvector1, yvector1)
%CREATEFIGURE(XVECTOR1,YVECTOR1)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 04-May-2011 13:34:15

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'0','100','200','300','400','500','600','700','800',''},...
    'XTick',[0 1200 2400 3600 4800 6000 7200 8400 9600 10000],...
    'Position',[0.132072538860104 0.170662905500705 0.792279792746114 0.795239774330042]);
box(axes1,'on');
hold(axes1,'all');

% Create xlabel
xlabel('LifeTime [min]','FontSize',24);

% Create ylabel
ylabel('Count','FontSize',20);

% Create bar
bar(xvector1,yvector1,'FaceColor',[0 0 0.5625]);
end