function fluoData=getImageData(gfpImage,rfpImage,orderNum,maskImage,timeInterval)
backGround=getBackGround(rfpImage(:,:,1));
rfpImage=rfpImage-backGround;
backGround=getBackGround(gfpImage(:,:,1));
gfpImage=gfpImage-backGround;
maskAll=getImpMark(orderNum,maskImage);
for i=1:size(gfpImage,3)
    gfpI=gfpImage(:,:,i);
    fluoData.gfpData(i)=mean(gfpI(maskAll(:,:,i)));
    rfpI=rfpImage(:,:,i);
    fluoData.rfpData(i)=mean(rfpI(maskAll(:,:,i)));
end
deltaP=deltaPCaculate(fluoData);
createfigure(timeInterval:timeInterval:timeInterval*size(gfpImage,3),[fluoData.gfpData;fluoData.rfpData],timeInterval*2:timeInterval:timeInterval*size(gfpImage,3),deltaP)
saveas(gcf,'deltaP figure')
end
function backGround=getBackGround(image)
image=image(:);
image=sort(image);
imageSize=numel(image);
backGround=mean(image(1:imageSize/10));
end
function maskAll=getImpMark(orderNum,bwImage)
if numel(orderNum)~=size(bwImage,3)
    disp('wrong orderNum')
    return
end
maskAll=false(size(bwImage));
for i=1:numel(orderNum)
    cc=regionprops(bwImage(:,:,i),'PixelIdxList');
    image=maskAll(:,:,i);
    image(cc(orderNum(i)).PixelIdxList)=1;
    maskAll(:,:,i)=image;
    maskAll(:,:,i)=bwmorph(maskAll(:,:,i),'dilate');
    maskAll(:,:,i)=imfill(maskAll(:,:,i),'holes');
end
end
function deltaP=deltaPCaculate(fluoData)
gfpData=smooth(fluoData.gfpData);
rfpData=smooth(fluoData.rfpData);
gfpData=gfpData/100;
rfpData=rfpData/176;
for i=2:numel(gfpData)
    deltaP(i-1)=((gfpData(i)-rfpData(i-1))*5/120-(rfpData(i)-rfpData(i-1)))/rfpData(i-1);
end
end
function createfigure(X1, YMatrix1, X2, Y1)
%CREATEFIGURE(X1,YMATRIX1,X2,Y1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 09-Nov-2013 15:20:06

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.35625 0.594173014145811 0.274791666666666 0.338362350380848]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'Marker','diamond','Color',[0 1 0]);
set(plot1(2),'Marker','^','Color',[1 0 0]);

% Create ylabel
ylabel('aveFluo','FontSize',20);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.35625 0.224156692056583 0.275520833333333 0.369967355821546]);
box(axes2,'on');
hold(axes2,'all');

% Create plot
plot(X2,Y1,'Parent',axes2);

% Create xlabel
xlabel('Time(min)','FontSize',20);

% Create ylabel
ylabel('delta P','FontSize',20);
end