function drawAveFluo(fluoResult)
A=fluoResult.fluoMatrix;
step=5;
for i=1:size(A,2)
ALine=A(:,i);
p(i)=mean(ALine(ALine~=0));
end
t=step:step:step*size(A,2);
aveFluofigure(t,p)
end
function aveFluofigure(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 30-Jan-2013 17:55:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.372395833333333 0.396180631120784 0.24375 0.366605005440696]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'MarkerEdgeColor',[1 0 0],'MarkerSize',15,'Marker','.',...
    'LineStyle','--');

% Create xlabel
xlabel('time/minute','FontSize',16);

% Create ylabel
ylabel('mean Intensity','FontSize',16);

% Create title
title('Intensity vs time','FontSize',16);
end