function detailsForAdjacentMatrix(clusterTree)
clusterCoefficientAbout(clusterTree);
end
function clusterCoefficientAbout(clusterTree)
distMatrix=full(clusterTree{end}.distMatrix);
matriceSize=size(distMatrix,1);
orderNum=1:matriceSize;
degree=zeros(1,matriceSize);
branchInfo=zeros(1,matriceSize);
for i=1:matriceSize
    branchInfo(i)=clusterTree{end}.bacteriaList(i,5);
    iLine=distMatrix(i,:);
    linkPoint=orderNum(iLine==1);
    degree(i)=numel(linkPoint);
    if isempty(linkPoint)
        clusterCoefficient(i)=0;
    end
    if numel(linkPoint)==1
        clusterCoefficient(i)=0;
    end
    if numel(linkPoint)>1
        linkMatrix=distMatrix(iLine,iLine);
        edgeNum=nnz(sparse(linkMatrix))/2;
        clusterCoefficient(i)=edgeNum/numel(linkPoint)/(numel(linkPoint)-1)*2;
    end
end
newTrace=1:max(degree);
kCC=zeros(numel(newTrace),1);
for i=2:numel(newTrace)
    kCC(i)=mean(clusterCoefficient(degree<=i+1&degree>=i-1));
end
kCC(:,2)=kCC;
kCC(:,1)=1:size(kCC,1);
kCC(isnan(kCC(:,2)),:)=[];
createCollectiveClusterCoeficientFigure(kCC(:,1), kCC(:,2));
end
function createCollectiveClusterCoeficientFigure(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 29-Mar-2013 21:27:09

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.667916666666667 0.815]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1);

% Create xlabel
xlabel('degree','FontSize',20);

% Create ylabel
ylabel('collective cluster coefficient','FontSize',20);
end