function degreeRad=logDegreeVsRadiusMap(bioTree,clusterTree,iframe)
bacteriaLength=40;
amp=0.025;
colorChoose=zeros(1000,3);
colorChoose(:,1)=0.5;
colorChoose(1:200,:)=colormap(jet(200));
close all
distMatrix=full(clusterTree{iframe}.distMatrix);
bacteriaList=clusterTree{iframe}.bacteriaList;
centroidInfo=zeros(size(bacteriaList,1),2);
for i=1:size(bacteriaList,1)
    iList=bacteriaList(i,:);
    if iList(3)==0
        centroidInfo(i,:)=bioTree{iList(1)}.root{iList(2)}.traceInfo.measurment{iList(4)}.Centroid;
    end
    if iList(3)~=0;
        centroidInfo(i,:)=bioTree{iList(1)}.node{iList(2)}.Out{iList(3)}.traceInfo.measurment{iList(4)}.Centroid;
    end
end
centroidMatrice=pdist2(centroidInfo,centroidInfo);
degreeRadius=zeros(size(bacteriaList,1),2);
for i=1:size(bacteriaList,1)
    iDist=distMatrix(i,:);
    degreeRadius(i,1)=numel(iDist(iDist==1));
    icentroid=centroidInfo(iDist==1,:);
    properCentroid=[mean(icentroid(:,1)),mean(icentroid(:,2))];
    degreeRadius(i,2)=(mean(pdist2(icentroid,properCentroid).^2)).^0.5;
end
degreeRadius(degreeRadius(:,1)<=1,:)=[];
degreeRadius=degreeRadius(:,end:-1:1);
degreeRadius(:,1)=degreeRadius(:,1)/bacteriaLength;
degreeRadius(:,1)=degreeRadius(:,1).^2;
degreeRadius=log10(degreeRadius);
degreeRad=twoDimGaussian(degreeRadius);
h=createSurfacefigure(degreeRad.y',degreeRad.x',degreeRad.Image*amp,colorChoose,iframe);
end
function result=twoDimGaussian(degreeRadius)
xMin=0;
yMin=0;
xMax=log10(600);
yMax=log10(300);
sigma1=log10(600)/60;
interval1=log10(600)/300;
sigma2=log10(300)/150;
interval2=log10(300)/300;
rowPos=xMin:interval1:xMax;
rowPos=rowPos';
columnPos=yMin:interval2:yMax;
resultImage=zeros(numel(rowPos),numel(columnPos));
for i=1:size(degreeRadius,1)
%     disp(i)
    rowGauss=1/(2*pi)^0.5/sigma1*exp(-(rowPos-degreeRadius(i,1)).^2/2/sigma1^2);
    columnGauss=1/(2*pi)^0.5/sigma2*exp(-(columnPos-degreeRadius(i,2)).^2/2/sigma2^2);
    resultImage=resultImage+rowGauss*columnGauss;
end
result.Image=resultImage;
result.numPoint=size(degreeRadius,1);
result.x=rowPos';
result.y=columnPos;
end
function h=createSurfacefigure(xdata,ydata,zdata,colorChoose,i)
%CREATEFIGURE(ZDATA1,YDATA1,XDATA1,CDATA1)
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 16-Apr-2013 19:57:26

% Create figure
figure1 = figure;
% Create axes
axes1 = axes('Parent',figure1);
xlim(axes1,[0 log10(300)]);
ylim(axes1,[0 log10(600)]);
hold(axes1,'all');

% Create surface
surface('Parent',axes1,'ZData',zdata,'YData',ydata,'XData',xdata,'CData',zdata,...
    'LineStyle','none');
colorChoose=colorChoose(1:ceil(max(max(zdata))),:);
colormap(colorChoose)
% Create title
title(strcat('frameNum=',num2str(i)),'FontSize',20);

% Create xlabel
xlabel('log10(degreeNum)','FontSize',20);

% Create ylabel
ylabel('log10(normallized radius.^2)','FontSize',20);
h=gcf;
end